solarconversionconstant: 0.194  #solar efficiency
uae: 172.0                    # Lumped Thermal Resistance W per 'C
tau: 374400.0 # house thermal time constant seconds
houseeffectivearea: 6.84  # Area in M2 exposed to sun
sghc: 0.89  # Solar Heat Gain Coefficient
hpbasepower: 1571.0 # heat pump power base consumption when running (will add temperature component)
#tsp: 22.2 # temperature setpoint 'C
tsp: 20.0 # temperature setpoint 'C
del: 0.5 # thermostat hysteresis
plugload: 5900 # plugload W
solarpaneleffectivearea: 52.16 # M2 solar panel
