federationManagerParameter:
  Step: 1.0
  Lookahead: 0.1
  RootPathEnvVarKey: CPSWT_ROOT
  RealTimeMode: 1
  FederationEndTime: 0
  Seed4Dur: 0
  AutoStart: 1
  FOMFilename: FedManager.fed
  ScriptFilename: script.xml
  LogDir: log
  LogLevel: NORMAL
  FederationName: FedManager
  StopScriptPath: Main/stop.sh
  FederateRTIInitWaitTime: 1000

server:
  type: simple
  applicationContextPath: /api
  connector:
    type: http
    port: 8083
    bindHost: 0.0.0.0

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger - %X{code} %msg %n"
    - type: file
      currentLogFilename: log/cpswtng-dwlog.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/cpswtng-dwlog-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger - %X{code} %msg %n"
